apiVersion: v1
kind: Service
metadata:
  name: pseudo-app-service
  namespace: nginx
spec:
  selector:
    app: pseudo-app # Matches the label in the deployment
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000